name: Quality control
on:
  push:

env:
  RUSTFLAGS: --deny warnings

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y libdrm-dev libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev libdisplay-info-dev
          rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2.7.8

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Test
        run: cargo test --all

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          sudo apt-get update;
          sudo apt-get install -y libdrm-dev libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev libseat-dev libdisplay-info-dev
          rustup toolchain install stable
#          rustup target add x86_64-unknown-linux-musl TODO: make blockers optional features

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

      - name: Build
        run: cargo build --all --release

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: release-build
          path: target/release/setwlkbmap