name: Quality control
on:
  push:

env:
  RUSTFLAGS: --deny warnings

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          rustup toolchain install stable
          rustup default stable
      - uses: Swatinem/rust-cache@v2.7.8

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

      - name: Clippy
        run: cargo clippy --all-targets

      - name: Test
        run: cargo test --all

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup target add x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Info
        run: |
          rustup --version
          cargo --version

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: release-build
          path: target/release/setwlkbmap