name: Quality control
on:
  push:

env:
  RUSTFLAGS: --deny warnings

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/' /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt install -qq -y libudev-dev
          rustup toolchain install stable
          rustup default stable
      - uses: Swatinem/rust-cache@v2.7.8

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Test
        run: cargo test --all

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/' /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt install -qq -y libudev-dev
          rustup toolchain install stable
          rustup default stable
      #          rustup target add x86_64-unknown-linux-musl TODO: make blockers optional features

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Info
        run: |
          rustup --version
          cargo --version

      - name: Build
        run: cargo build --all --release

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: release-build
          path: target/release/setwlkbmap